# Generated by Django 6.1 on 2026-08-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('company_name', models.CharField(help_text='Organization name (e.g. City Traffic Authority, University, Manufacturing Plant).', max_length=200, verbose_name='Company / Institution Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Work Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('service_vehicles_people', models.BooleanField(default=False, verbose_name='Vehicles & People Detection (Traffic/Roads)')),
                ('service_face_recognition', models.BooleanField(default=False, verbose_name='Face Recognition & Attendance (Institutions)')),
                ('service_object_count', models.BooleanField(default=False, verbose_name='Industrial Object Counter (Factories)')),
                ('camera_count', models.CharField(choices=[('1-5', '1 - 5 Cameras'), ('6-20', '6 - 20 Cameras'), ('21-50', '21 - 50 Cameras'), ('50+', '50+ Enterprise Cameras')], default='1-5', max_length=50, verbose_name='Estimated Camera Count')),
                ('message', models.TextField(blank=True, verbose_name='Project Notes / Use Case Details')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Contacted'), ('approved', 'Approved / Activated'), ('closed', 'Closed')], default='pending', max_length=30, verbose_name='Lead Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
