# Generated by Django 6.1 on 2026-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='service_face_recognition',
        ),
    ]
