# Generated by Django 6.1 on 2026-10-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_demorequest_service_face_recognition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demorequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support Inquiry', 'verbose_name_plural': 'Support Inquiries'},
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='camera_count',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='service_object_count',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='service_vehicles_people',
        ),
        migrations.AddField(
            model_name='demorequest',
            name='query_type',
            field=models.CharField(choices=[('technical_support', 'Technical Support'), ('project_deployment', 'Project / Deployment Query'), ('documentation', 'Documentation & General Questions'), ('other', 'Other Inquiry')], default='technical_support', max_length=50, verbose_name='Subject / Query Type'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Organization name (optional).', max_length=200, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
