# Generated by Django 6.1 on 2026-08-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_vehicles_people', models.BooleanField(default=True, help_text='Enables YOLOv8 + ByteTrack vehicle and pedestrian detection for traffic/road monitoring.', verbose_name='Vehicles & People Detection')),
                ('has_face_recognition', models.BooleanField(default=False, help_text='Enables face matching against uploaded reference images for colleges/institutions.', verbose_name='Face Recognition & Attendance')),
                ('has_object_count', models.BooleanField(default=False, help_text='Enables production line & conveyor belt item counting for factories.', verbose_name='Industrial Object Counter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Service Profile',
                'verbose_name_plural': 'User Service Profiles',
            },
        ),
    ]
