# Generated by Django 6.1 on 2026-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userserviceprofile',
            name='has_face_recognition',
        ),
    ]
