# Generated by Django 6.1 on 2026-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'getting-started'. Auto-populated from title.", unique=True)),
                ('content_markdown', models.TextField(blank=True, help_text='Paste or upload Markdown content here. Code fences with language tags are syntax-highlighted.')),
                ('category', models.CharField(help_text="Group label shown in the sidebar, e.g. 'Getting Started', 'Configuration'.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order within the category. Lower numbers appear first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documentation Page',
                'verbose_name_plural': 'Documentation Pages',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
