# Generated by Django 6.1 on 2026-08-24 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Front Door' or 'Parking Lot'.", max_length=100)),
                ('source_url', models.CharField(help_text="Video source: webcam index (e.g. '0') or full RTSP URL (e.g. 'rtsp://user:pass@192.168.1.100:554/stream'). WARNING: RTSP URLs with credentials are stored as-is in v1.", max_length=500)),
                ('tracker_enabled', models.BooleanField(default=True, help_text='Enable ByteTrack multi-object tracking. Disable for detection-only mode.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive cameras are excluded from the dashboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
            },
        ),
    ]
