# Generated by Django 6.1 on 2026-08-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(help_text="Human-readable name, e.g. 'Front Door' or 'Main Road Intersection'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='source_url',
            field=models.CharField(help_text="Video source: webcam index (e.g. '0') or full RTSP URL.", max_length=500),
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(default=-1)),
                ('class_name', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox_x1', models.FloatField(default=0.0)),
                ('bbox_y1', models.FloatField(default=0.0)),
                ('bbox_x2', models.FloatField(default=0.0)),
                ('bbox_y2', models.FloatField(default=0.0)),
                ('line_crossing_status', models.CharField(default='none', max_length=32)),
                ('frame_number', models.IntegerField(default=0)),
                ('snapshot_path', models.CharField(blank=True, help_text='Relative media path to the saved object snapshot.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='nvr.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Event',
                'verbose_name_plural': 'Detection Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('person_id', models.CharField(blank=True, help_text='e.g. STU-2024-042 or EMP-1092', max_length=50, verbose_name='Student / Employee ID')),
                ('department', models.CharField(blank=True, help_text='e.g. Computer Science - Year 3', max_length=100, verbose_name='Department / Class Section')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faces/references/', verbose_name='Reference Face Image')),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Reference',
                'verbose_name_plural': 'Face References',
                'ordering': ['person_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.92)),
                ('status', models.CharField(default='Present', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='nvr.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('face_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='nvr.facereference')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ObjectCountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(default='Manufactured Unit', max_length=100)),
                ('total_count', models.IntegerField(default=0)),
                ('in_count', models.IntegerField(default=0)),
                ('out_count', models.IntegerField(default=0)),
                ('rate_per_minute', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_records', to='nvr.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Object Count Record',
                'verbose_name_plural': 'Object Count Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
