# Generated by Django 6.1 on 2026-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvr', '0002_alter_camera_name_alter_camera_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Natural-language description for Qwen-VL or manual annotation.'),
        ),
    ]
