# Generated by Django 6.1 on 2026-09-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvr', '0003_detectionevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='night_threshold',
            field=models.FloatField(default=60.0, help_text='Grayscale mean intensity threshold below which scene is classified as Night Mode.'),
        ),
        migrations.AddField(
            model_name='camera',
            name='scene_mode',
            field=models.CharField(choices=[('day', 'Day Mode'), ('night', 'Night Mode')], default='day', help_text='Current detected or default scene mode.', max_length=10),
        ),
        migrations.CreateModel(
            name='MonitoringZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Restricted Zone 1', help_text="User-defined zone label, e.g. 'Warehouse Gate' or 'Perimeter Fence'.", max_length=100)),
                ('zone_type', models.CharField(choices=[('polygon', 'Restricted Area (Polygon)'), ('line', 'Tripwire (Line Crossing)')], default='polygon', max_length=20)),
                ('coordinates', models.JSONField(default=list, help_text='List of normalized points [[x, y], ...] representing polygon vertices or line endpoints.')),
                ('target_classes', models.JSONField(blank=True, default=list, help_text="List of target classes to monitor (e.g. ['person']). Empty implies all classes.")),
                ('is_active', models.BooleanField(default=True, help_text='Whether intrusion detection is currently active for this zone.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_zones', to='nvr.camera')),
            ],
            options={
                'verbose_name': 'Monitoring Zone',
                'verbose_name_plural': 'Monitoring Zones',
                'ordering': ['created_at'],
            },
        ),
    ]
