# Generated by Django 6.1 on 2026-09-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvr', '0004_camera_night_threshold_camera_scene_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('IDLE', 'Idle / Not Started'), ('AWAITING_USERNAME', 'Awaiting Username'), ('AWAITING_PASSWORD', 'Awaiting Password'), ('AUTHENTICATED_IDLE', 'Authenticated & Ready'), ('AWAITING_FEEDBACK', 'Awaiting Feedback')], default='IDLE', max_length=32)),
                ('pending_username', models.CharField(blank=True, max_length=150)),
                ('last_intent', models.CharField(blank=True, max_length=64)),
                ('last_query', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Session',
                'verbose_name_plural': 'Telegram Sessions',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='TelegramFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('query_text', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=64)),
                ('is_helpful', models.BooleanField(help_text='True if Yes, False if No')),
                ('raw_feedback', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='nvr.telegramsession')),
            ],
            options={
                'verbose_name': 'Telegram Feedback',
                'verbose_name_plural': 'Telegram Feedback Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
