# Generated by Django 6.1 on 2026-09-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvr', '0005_telegramsession_telegramfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsession',
            name='user',
        ),
        migrations.CreateModel(
            name='AlertConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Alert Investigation', max_length=200)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the alert context (camera, track, object class, timestamp).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='nvr.camera')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='nvr.detectionevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Conversation',
                'verbose_name_plural': 'Alert Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Operator'), ('assistant', 'SemanticEdge Assistant'), ('system', 'System')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Structured evidence metadata, snapshots, tool outputs, or action links.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nvr.alertconversation')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TelegramFeedback',
        ),
        migrations.DeleteModel(
            name='TelegramSession',
        ),
    ]
