# Generated by Django 6.1 on 2026-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvr', '0006_remove_telegramsession_user_alertconversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facereference',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='FaceReference',
        ),
    ]
